# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: 
  facebook: 
  instagram: fanlvlgh
  github: fanlv

user:
  name: Ryo
  avatar: https://upload-images.jianshu.io/upload_images/12321605-8743f44f528a9c79.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
  location: China
  description: 行万里路，读万卷书
  footnotes: 博学之，审问之，慎思之，明辨之，笃行之

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: fanlv/blog # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon:

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id: 2c076421eb9f21a0a143f8ee9c4ab171

# picture of about page
about_pic: https://upload-images.jianshu.io/upload_images/12321605-b7625e3ab18e6cb5.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240
